travis:
  secure:
    BINSTAR_TOKEN: gBLGrNyJEpQq0P3onhWmIDL5oafBr6cR8ZgkNFTAq0fSBh5XbWrIYT1GRJxArFwVuLpvp8dE1GEkDj8x/Gr+SX6IgSgB4zXr+rLVsjal295LaNsAsFXlJb1GyakamM/i4EvQg2yeeswrVQBQD4Y86s0s5pRMdZ40LAYTzAD9leZ2SQKq0osEDeAUUxzXDWMemzAPSpD6YaMMPWKJJ/3ukKZvJUn2lTqVXbkWUZ8HrbgsQU3bnXiKRE5xmYWTywIwXyk9+MpJ4gMld9Wojqe/g3Cv2oSfY3OAuqxacmKkWUfYb/UBPqH4kstHZa0JgZdCOQ4zIYcJD4h+gWwW357hiNSbhjRRJ4V0b2SAJgsxkYGoIMiaouGxsG3s4uvOJZbjmwQEmzB4o5bKJCiYj9mWTVfRS6/qNKyPJxrx30QW6LY/vjvNibuZj7DHaMOS+EXmUA1hfTjyR3k8+jlfKUOhqng734p6hacDx4OeDplPtutRL1A4tPERwg5aG0yd3xkUCAv7iig3CVuO0kb5xF9YrbBZg/uGyoUF1Cs74xDQu/dKCe7Hz/PIc5fUS5S5IuPtlVZcmX8Nvx/+PQv7VXPNI50LSDYGnBoXJTRq8+Co3C+xj7TX6wEGNvCKVf6NjglCTSVEkRcNLuZRtFBwdARiRNRNKPEg7ENd3biZBggyaKk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
